#
# SQL Export
# Created by Querious (1048)
# Created: 2016년 10월 24일 오후 9시 30분 30초 GMT+9
# Encoding: Unicode (UTF-8)
#


DROP DATABASE IF EXISTS `UzysHapiReactBoilerplate`;
CREATE DATABASE `UzysHapiReactBoilerplate` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
USE `UzysHapiReactBoilerplate`;




SET @PREVIOUS_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;


DROP TABLE IF EXISTS `USER`;


CREATE TABLE `USER` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `login_email` varchar(128) DEFAULT NULL,
  `login_pw` varchar(128) DEFAULT NULL,
  `contact` varchar(128) DEFAULT NULL,
  `role` enum('ADMIN','USER') NOT NULL DEFAULT 'USER',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_login_email` (`login_email`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;




SET FOREIGN_KEY_CHECKS = @PREVIOUS_FOREIGN_KEY_CHECKS;


SET @PREVIOUS_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;


LOCK TABLES `USER` WRITE;
ALTER TABLE `USER` DISABLE KEYS;
INSERT INTO `USER` (`id`, `login_email`, `login_pw`, `contact`, `role`) VALUES 
	(1,'test@test.com','$2a$10$M86DLVJ6tyAXBdpyAI0VeeWwsGs6DBiQsSwTK2K715/kLf85SO/RC',NULL,'ADMIN'),
	(2,'aa@a.com','$2a$10$9VNG53zFCVjqj554/gziQ.L5A1NgsCnyOHuIoMQqKF/fqt1Rs61be',NULL,'USER'),
	(3,'test@ttt.com','$2a$10$.KtoC5Nqj0B4pqoCM6nIiOsvC9.AI4HMQrTVCOow2COH9sC.Jskp6',NULL,'USER'),
	(4,'aaa@aaa.com','$2a$10$I25bBPAzoYVDBr/PuotKWeJaxevlOLFSYTpFE4rMSPGuGkGAPiYTi',NULL,'USER'),
	(6,'test@test2.com','$2a$10$zzrg1/3Kr8MCGQs1XODaqORuxzEHDdDyFrZuWli1Tn2mmY28A3i2y',NULL,'USER');
ALTER TABLE `USER` ENABLE KEYS;
UNLOCK TABLES;




SET FOREIGN_KEY_CHECKS = @PREVIOUS_FOREIGN_KEY_CHECKS;


