//USER ACTION
export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const PUT_USER_DATA = 'PUT_USER_DATA';
export const GET_USER_DATA = 'GET_USER_DATA';
export const WAITING_USER_DATA = 'WAITING_USER_DATA';
export const FAILED_USER_DATA = 'FAILED_USER_DATA';

//Github
export const RECEIVE_GITHUB_DATA = 'RECEIVE_GITHUB_DATA';
export const RECEIVE_FAILED_GITHUB_DATA = 'RECEIVE_FAILED_GITHUB_DATA';
export const REQUEST_GITHUB_DATA = 'REQUEST_GITHUB_DATA';
